---
config:
  layout: elk
---

erDiagram
    Пользователь ||--o{ Документ : владеет
    Пользователь {
        int id
        string имя
        string email
        string телефон
        string роль "клиент, админ, оператор магазина"
    }

    Документ ||--o{ ВерсияДокумента : имеет
    Документ ||--o{ ЗаказПечати : запрошен_для
    Документ {
        int id
        string название
        string тип "текст, презентация"
        int владелец "userId"
        int ссылка на шаблон
    }

    ВерсияДокумента ||--o{ ШаблонДокумента :  может_использовать
    ВерсияДокумента {
        int id
        int ссылка на документ
        int номер версии
        datetime дата создания
        string ссылка на содержимое "storageId"
    }

    ШаблонДокумента ||--o{ Документ :  используется_в
    ШаблонДокумента {
        int id
        string название
        string категория "бизнес, учеба и т.д."
    }

    ЗаказПечати ||--|| Транзакция : оплачивается_через
    ЗаказПечати ||--|| Магазин : запланирован_в
    ЗаказПечати {
        int id
        int документ "documentId"
        int магазин "storeId"
        int количество_копий
        string параметры "цвет, формат, двусторонняя"
        string статус "запланирован, печатается, готов, выдан"
        datetime расписание "дата/время"
    }

    Транзакция ||--|| Магазин : связан_с
    Транзакция {
        int id
        int привязка_к_магазину "storeId"
        decimal сумма
        string статус "успешно, отклонено"
        string метод_оплаты "онлайн, наличные в магазине"
    }

    Магазин ||--o{ ЗаказПечати : получает
    Магазин {
        int id
        string название
        string адрес
    }
